// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKTlBeFkWYByUvGmfXP9751mWaR3exhY',
    appId: '1:1071502381770:web:c5f255bdf5deefd43f5a33',
    messagingSenderId: '1071502381770',
    projectId: 'campus-counselling-app',
    authDomain: 'campus-counselling-app.firebaseapp.com',
    storageBucket: 'campus-counselling-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQF82WD6NSgY6ZJ1hxzJ6BP6Qw30HDWs0',
    appId: '1:1071502381770:android:8d29fbfc6090df2d3f5a33',
    messagingSenderId: '1071502381770',
    projectId: 'campus-counselling-app',
    storageBucket: 'campus-counselling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk3vI0uksHVsTIJezwGbFXsTvwya9KsuI',
    appId: '1:1071502381770:ios:3021b6f8d891bd003f5a33',
    messagingSenderId: '1071502381770',
    projectId: 'campus-counselling-app',
    storageBucket: 'campus-counselling-app.firebasestorage.app',
    iosClientId: '1071502381770-u81pbdgnvtcccnd8mrfjvntbr0m7lg2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusCounselingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk3vI0uksHVsTIJezwGbFXsTvwya9KsuI',
    appId: '1:1071502381770:ios:3021b6f8d891bd003f5a33',
    messagingSenderId: '1071502381770',
    projectId: 'campus-counselling-app',
    storageBucket: 'campus-counselling-app.firebasestorage.app',
    iosClientId: '1071502381770-u81pbdgnvtcccnd8mrfjvntbr0m7lg2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusCounselingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKTlBeFkWYByUvGmfXP9751mWaR3exhY',
    appId: '1:1071502381770:web:4da856137bfb0dd83f5a33',
    messagingSenderId: '1071502381770',
    projectId: 'campus-counselling-app',
    authDomain: 'campus-counselling-app.firebaseapp.com',
    storageBucket: 'campus-counselling-app.firebasestorage.app',
  );
}
